In [9]:
from tensorflow.keras.preprocessing.text import one_hot

In [10]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [11]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [12]:
## Define the vocabulary size
voc_size=10000

In [13]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [14]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1963, 4182, 4230, 721],
 [1963, 4182, 4230, 8916],
 [1963, 4979, 4230, 3646],
 [8697, 8307, 5856, 5537, 8426],
 [8697, 8307, 5856, 5537, 7703],
 [3547, 1963, 9973, 4230, 2969],
 [3261, 5313, 7349, 5537]]

In [15]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [16]:
import numpy as np

In [17]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1963 4182 4230  721]
 [   0    0    0    0 1963 4182 4230 8916]
 [   0    0    0    0 1963 4979 4230 3646]
 [   0    0    0 8697 8307 5856 5537 8426]
 [   0    0    0 8697 8307 5856 5537 7703]
 [   0    0    0 3547 1963 9973 4230 2969]
 [   0    0    0    0 3261 5313 7349 5537]]


In [18]:
## feature representation
dim=10

In [19]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 64ms/step


array([[[ 0.00834855,  0.03494388,  0.04446448,  0.02572245,
         -0.04913632, -0.02921733,  0.04324389, -0.02593329,
          0.01187252, -0.04867159],
        [ 0.00834855,  0.03494388,  0.04446448,  0.02572245,
         -0.04913632, -0.02921733,  0.04324389, -0.02593329,
          0.01187252, -0.04867159],
        [ 0.00834855,  0.03494388,  0.04446448,  0.02572245,
         -0.04913632, -0.02921733,  0.04324389, -0.02593329,
          0.01187252, -0.04867159],
        [ 0.00834855,  0.03494388,  0.04446448,  0.02572245,
         -0.04913632, -0.02921733,  0.04324389, -0.02593329,
          0.01187252, -0.04867159],
        [-0.01195526,  0.03338141,  0.01772081, -0.03580382,
         -0.03108076, -0.02328293,  0.04709274,  0.02003678,
         -0.03934666,  0.04311105],
        [-0.00925984,  0.037884  , -0.03635082, -0.00842901,
         -0.02460886, -0.00275571, -0.00312295,  0.03669192,
          0.01910419,  0.0366453 ],
        [ 0.02422429, -0.00632085, -0.03742016,  0.0

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 1963, 4182, 4230,  721])

In [23]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 34ms/step


array([[ 0.00834855,  0.03494388,  0.04446448,  0.02572245, -0.04913632,
        -0.02921733,  0.04324389, -0.02593329,  0.01187252, -0.04867159],
       [ 0.00834855,  0.03494388,  0.04446448,  0.02572245, -0.04913632,
        -0.02921733,  0.04324389, -0.02593329,  0.01187252, -0.04867159],
       [ 0.00834855,  0.03494388,  0.04446448,  0.02572245, -0.04913632,
        -0.02921733,  0.04324389, -0.02593329,  0.01187252, -0.04867159],
       [ 0.00834855,  0.03494388,  0.04446448,  0.02572245, -0.04913632,
        -0.02921733,  0.04324389, -0.02593329,  0.01187252, -0.04867159],
       [-0.01195526,  0.03338141,  0.01772081, -0.03580382, -0.03108076,
        -0.02328293,  0.04709274,  0.02003678, -0.03934666,  0.04311105],
       [-0.00925984,  0.037884  , -0.03635082, -0.00842901, -0.02460886,
        -0.00275571, -0.00312295,  0.03669192,  0.01910419,  0.0366453 ],
       [ 0.02422429, -0.00632085, -0.03742016,  0.02974451,  0.02628747,
         0.0252846 , -0.00370046, -0.01631789